app/routes/web.php
<?php declare(strict_types=1);

use App\Http\Controllers\Admin\Home\MetaController;
use App\Http\Controllers\HomeController;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Support\Facades\Route;
use SP\Admin\Http\Middleware\Locale;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home');

Route::prefix('admin')
    ->name('admin.')
    ->middleware([
        'web',
        Locale::class,
        AuthenticateSession::class,
    ])->group(static function () {
        // home meta
        Route::get('home/metas', [MetaController::class, 'show'])->name('home.metas.show');
        Route::get('home/metas/edit', [MetaController::class, 'edit'])->name('home.metas.edit');
        Route::match(['put', 'patch'], 'home/metas', [MetaController::class, 'update'])->name('home.metas.update');
    });

app/app/Models/Home/Meta.php
<?php
declare(strict_types=1);

namespace App\Models\Home;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use SP\Admin\Models\Model;
use Illuminate\Support\Carbon;

/**
 * Homepage meta data.
 *
 * @property int $id
 * @property string $title
 * @property string $description
 * @property string $image
 * @property string|Carbon $created_at
 * @property string|Carbon $updated_at
 *
 * @package App\Models\Home
 */
final class Meta extends Model
{
    use HasFactory;

    public const IMAGE_DIRECTORY = 'home';

    /**
     * The table associated with the model.
     *
     * @var string
     */
    protected $table = 'home_metas';
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title',
        'description',
        'image',
    ];

    /**
     * Indicates if the IDs are auto-incrementing.
     *
     * @var bool
     */
    public $incrementing = false;

    /**
     * {@inheritDoc}
     */
    public static function attributeLabels(): array
    {
        return [
            'title' => trans('Page Title'),
            'description' => trans('Page Description'),
            'image' => trans('Image'),
            'created_at' => trans('Creation Date'),
            'updated_at' => trans('Modification Date'),
        ];
    }

}

app/app/functions.php
<?php declare(strict_types=1);

if (!\function_exists('image_placeholder')) {
    /**
     * Image placeholder.
     *
     * @param array $options [width, height, extension, bg_color, txt_color, text, return_type (path|url)]
     * @return string|null Path to image or NULL on failure
     */
    function image_placeholder(array $options): ?string
    {
        $w = (string)($options['width'] ?? 300);
        $h = (string)($options['height'] ?? 170);
        $size = "{$w}x{$h}";

        $extension = $options['extension'] ?? 'jpg';

        $bg_color = $options['bg_color'] ?? null;
        $txt_color = $options['txt_color'] ?? null;
        $colors = '';
        if ($bg_color !== null && $txt_color !== null) {
            $colors = "/$bg_color/$txt_color";
        }

        $text = isset($options['text']) ? urlencode(e($options['text'])) : urlencode(config('app.name'));

        $return_type = isset($options['return_type']) && in_array($options['return_type'],
            ['path', 'url']) ? $options['return_type'] : 'url';

        $service_url = 'https://via.placeholder.com';
        $url = "$service_url/$size{$colors}.$extension?text=$text";

        if ($return_type === 'url') {
            return $url;
        }

        try {
            $image_source = file_get_contents($url);
            $tmp_image = sys_get_temp_dir() . '/' . md5((string)time());
            file_put_contents($tmp_image, $image_source);
        } catch (\Throwable) {
            $tmp_image = null;
        }

        return $tmp_image;
    }
}

app/app/sitemap.php
<?php declare(strict_types=1);

return [
    'static' => [
        [
            'location' => static fn(): string => url(''),
            'priority' => 0.9,
        ],
    ],
    'dynamic' => [],
];

app/app/trash_bin.php
<?php declare(strict_types=1);

return [

];

app/app/Http/Controllers/Admin/Home/MetaController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers\Admin\Home;

use App\Http\Requests\Home\Meta\UpdateRequest;
use App\Models\Home\Meta;
use App\Repositories\Home\MetaRepository;
use App\UseCases\Home\MetaImageService;
use Illuminate\Database\Eloquent\MassAssignmentException;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;
use SP\Admin\Http\Controllers\AdminController;

/**
 * CRUD for home meta data.
 *
 * @package App\Http\Controllers\Admin\Home
 */
final class MetaController extends AdminController
{
    /**
     * MetaController constructor.
     *
     * @param MetaRepository $repository
     */
    public function __construct(private MetaRepository $repository)
    {
        parent::__construct();

//        $this->authorizeResource(Meta::class);
    }

    /**
     * {@inheritDoc}
     */
    protected function resourceMethodsWithoutModels(): array
    {
        return ['show', 'edit', 'update'];
    }

    /**
     * Displays the specified resource.
     *
     * @return View
     */
    public function show(): View
    {
        return view('admin.home.metas.show', [
            'modeldetails_config' => $this->repository->modelDetailsConfig(),
        ]);
    }

    /**
     * Shows the form for editing the specified resource.
     *
     * @param MetaImageService $imageService
     * @return View
     */
    public function edit(MetaImageService $imageService): View
    {
        $model = $this->repository->getData();

        return view('admin.home.metas.edit', [
            'model' => $model,
            'image_url' => filled($model->image) ? $imageService->urlOriginal($model->image) : '',
        ]);
    }

    /**
     * Updates the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @return RedirectResponse
     * @throws MassAssignmentException
     */
    public function update(UpdateRequest $request): RedirectResponse
    {
        $data = $request->validated();
        $model = $this->repository->getData();

        if (!$model->fill($data)->save()) {
            return back()->with('error', trans('Error updating.'));
        }

        return redirect()
            ->route('admin.home.metas.show')
            ->with('success', trans('The Record has been updated.'));
    }

}

app/app/Http/Controllers/Controller.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers;

use Artesaos\SEOTools\Traits\SEOTools;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

/**
 * Base controller.
 *
 * @package App\Http\Controllers
 */
class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
    use SEOTools;

    /**
     * Controller constructor.
     */
    public function __construct()
    {
        $default_title = config('seotools.meta.defaults.title');
        if ($default_title !== false) {
            config([
                'seotools.meta.defaults.title' => config('app.name'),
            ]);
        }
    }

}

app/app/Http/Controllers/HomeController.php
<?php
declare(strict_types=1);

namespace App\Http\Controllers;

use App\Repositories\Home\MetaRepository;
use Illuminate\View\View;

/**
 * Homepage controller.
 *
 * @package App\Http\Controllers
 */
final class HomeController extends Controller
{
    /**
     * Displays homepage.
     *
     * @param MetaRepository $metaRepository
     * @return View
     */
    public function index(MetaRepository $metaRepository): View
    {
        // page meta data
        $metaData = $metaRepository->getFullData();

        $this->seo()->setTitle($metaData['title']);
        $this->seo()->setDescription($metaData['description']);
        $this->seo()->addImages($metaData['image']);

        return view('home.site');
    }

}

app/resources/views/admin/home/metas/_form.blade.php
<?php /** @var App\Models\Home\Meta $model */ ?>

{{ html()->modelForm($model, $method, $route)->attribute('enctype', 'multipart/form-data')->open() }}


<div class="form-group">
    {{ html()->label($model::getAttributeLabel('title'), 'title') }}

    {{ html()->text('title')->class([
        'form-control',
        'is-invalid' => $errors->has('title'),
    ]) }}

    @error('title')
    {{ html()->span($message)->class('invalid-feedback') }}
    @enderror
</div>


<div class="form-group">
    {{ html()->label($model::getAttributeLabel('description'), 'description') }}

    {{ html()->textarea('description')->class([
        'form-control',
        'is-invalid' => $errors->has('description'),
    ]) }}

    @error('description')
    {{ html()->span($message)->class('invalid-feedback') }}
    @enderror
</div>


@if($model->image)
    <img class="img-thumbnail" src="{{ $image_url ?? '' }}" alt="">
@endif

<div class="custom-file mt-3 mb-4">
    {{ html()->file('image')->class([
        'custom-file-input',
        'is-invalid' => $errors->has('image'),
    ]) }}

    {{ html()->label($model::getAttributeLabel('image'), 'image')
        ->class('custom-file-label')
        ->data('browse', trans('Choose file')) }}

    @error('image')
    {{ html()->span($message)->class('invalid-feedback') }}
    @enderror
</div>

@if($model->image)
    <div class="custom-control custom-checkbox">
        {{ html()->checkbox('del_image')->class([
            'custom-control-input',
            'is-invalid' => $errors->has('del_image')
        ]) }}

        {{ html()->label(__('Delete file'), 'del_image')->class('custom-control-label') }}

        @error('del_image')
        {{ html()->span($message)->class('invalid-feedback') }}
        @enderror
    </div>
@endif


{{ html()->submit($submit['label'])->class('mt-3 btn btn-' . $submit['type']) }}


{{ html()->closeModelForm() }}

app/resources/views/admin/home/metas/edit.blade.php
@extends('admin::layouts.pages')

@push('breadcrumbs')
    <li class="breadcrumb-item"><a href="{{ route('admin.home.metas.show') }}">{{ __('Meta data of the Homepage') }}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{ __('Edit') }}</li>
@endpush

@section('title', __('Meta data of the Homepage') . ': ' . __('Edit'))

@section('content')

    @include('admin.home.metas._form', [
        'method' => 'put',
        'route' => route('admin.home.metas.update'),
        'submit' => [
            'type' => 'primary',
            'label' => __('Save'),
        ]
    ])

@endsection

app/resources/views/admin/home/metas/show.blade.php
@extends('admin::layouts.pages')

@push('breadcrumbs')
    <li class="breadcrumb-item active" aria-current="page">{{ __('Meta data of the Homepage') }}</li>
@endpush

@section('title', __('Meta data of the Homepage'))

@section('content')

    <div class="d-flex mb-3">
        <a class="btn btn-primary mr-2" href="{{ route('admin.home.metas.edit') }}">{{ __('Edit') }}</a>
    </div>

    @modelDetails($modeldetails_config)

@endsection

app/resources/views/home/site.blade.php
@extends('layouts.main')

@section('body')
    <p>Wellcome !!!</p>
@endsection

app/resources/views/layouts/main.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="Content-Security-Policy" content="block-all-mixed-content">
    <meta http-equiv="X-DNS-Prefetch-Control" content="on">

    <meta name="csrf-token" content="{{ csrf_token() }}">

    <base href="{{ url('/') }}">

    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link rel="dns-prefetch" href="//fonts.googleapis.com">

    <link rel="preconnect" href="//fonts.gstatic.com" crossorigin>
    <link rel="preconnect" href="//fonts.googleapis.com" crossorigin>

    {!! app('seotools')->generate(true) !!}

    @prepend('styles')
        <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    @endprepend
    @stack('styles')

    {!! analytics() !!}
    {!! head_scripts() !!}
</head>
<body>

{{--body--}}
@yield('body')

@prepend('scripts')
    <script src="{{ asset('js/app.js') }}"></script>
@endprepend
@stack('scripts')

{!! bottom_scripts() !!}
</body>
</html>